[alias]
b = "build"
c = "check"
r = "run"
t = "test"
build-release = "build --release"

[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[net]
retry = 3
git-fetch-with-cli = true

[env]
RUST_BACKTRACE = "1"
